#!/usr/bin/env python3
"""Regenerate per-directory index.md files from node frontmatter.

Indexes are generated, never hand-edited (the root index.md is the one
hand-maintained index; this script does not touch it). Run from the repo root:

    python3 scripts/build_indexes.py
"""

import sys
from pathlib import Path

DIRS = ["concepts", "procedures", "law", "municipalities", "scenarios"]

HEADER = (
    "<!-- Generated by scripts/build_indexes.py — do not hand-edit. -->\n\n"
    "# {title}\n\n"
)

TITLES = {
    "concepts": "Concepts",
    "procedures": "Procedures",
    "law": "Law",
    "municipalities": "Municipalities",
    "scenarios": "Scenarios",
}


def read_frontmatter(path: Path) -> dict:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fm = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t", "-")):
            key, value = line.split(":", 1)
            fm[key.strip()] = value.strip().strip('"')
    return fm


def build(root: Path) -> None:
    for d in DIRS:
        directory = root / d
        if not directory.is_dir():
            continue
        entries = []
        for node in sorted(directory.glob("*.md")):
            if node.name == "index.md":
                continue
            fm = read_frontmatter(node)
            title = fm.get("title", node.stem)
            description = fm.get("description", "")
            entries.append(f"- [{title}]({node.name}) - {description}")
        out = HEADER.format(title=TITLES.get(d, d.title())) + "\n".join(entries) + "\n"
        (directory / "index.md").write_text(out, encoding="utf-8")
        print(f"wrote {d}/index.md ({len(entries)} entries)")


if __name__ == "__main__":
    build(Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd())
